import type { Job, Candidate } from './definitions';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    description: 'We are looking for a an experienced Frontend Engineer to join our team...',
    requirements: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    status: 'Open',
    postedAt: '2024-05-01',
    postedBy: 'admin-user-id',
  },
  {
    id: '2',
    title: 'Product Manager',
    department: 'Product',
    description: 'We are seeking a Product Manager to own the roadmap for our core product...',
    requirements: ['Agile', 'JIRA', 'Market Research'],
    status: 'Open',
    postedAt: '2024-05-10',
    postedBy: 'admin-user-id',
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    department: 'Design',
    description: 'Join our design team to create beautiful and intuitive user experiences...',
    requirements: ['Figma', 'User Research', 'Prototyping'],
    status: 'Closed',
    postedAt: '2024-04-20',
    postedBy: 'admin-user-id',
  },
    {
    id: '4',
    title: 'Backend Developer',
    department: 'Engineering',
    description: 'Responsible for server-side web application logic and integration of the work frontend developers do.',
    requirements: ['Node.js', 'Express', 'MongoDB'],
    status: 'Open',
    postedAt: '2024-05-15',
    postedBy: 'admin-user-id',
  },
    {
    id: '5',
    title: 'DevOps Engineer',
    department: 'Engineering',
    description: 'Seeking a DevOps engineer to work on our deployment and infrastructure.',
    requirements: ['Docker', 'Kubernetes', 'AWS'],
    status: 'Open',
    postedAt: '2024-05-18',
    postedBy: 'admin-user-id',
  },
];

export const candidates: Candidate[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '123-456-7890',
    skills: ['React', 'TypeScript', 'Node.js'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '1',
    userId: 'user-alice-id',
    status: 'Shortlisted',
    appliedAt: '2024-05-02',
  },
  {
    id: '2',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '234-567-8901',
    skills: ['Agile', 'Scrum', 'JIRA'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '2',
    userId: 'user-bob-id',
    status: 'Interviewed',
    appliedAt: '2024-05-11',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '345-678-9012',
    skills: ['Figma', 'Sketch', 'Adobe XD'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '3',
    userId: 'user-charlie-id',
    status: 'Hired',
    appliedAt: '2024-04-22',
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    phone: '456-789-0123',
    skills: ['React', 'Next.js', 'GraphQL'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '1',
    userId: 'user-diana-id',
    status: 'Applied',
    appliedAt: '2024-05-05',
  },
  {
    id: '5',
    name: 'Ethan Hunt',
    email: 'ethan.h@example.com',
    phone: '567-890-1234',
    skills: ['Node.js', 'MongoDB', 'Express'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '4',
    userId: 'user-ethan-id',
    status: 'Rejected',
    appliedAt: '2024-05-16',
  },
   {
    id: '6',
    name: 'Fiona Glenanne',
    email: 'fiona.g@example.com',
    phone: '678-901-2345',
    skills: ['Docker', 'AWS', 'Terraform'],
    resumeUrl: '/resume-placeholder.pdf',
    jobId: '5',
    userId: 'user-fiona-id',
    status: 'Applied',
    appliedAt: '2024-05-20',
  },
];
